<?php

declare(strict_types=1);

namespace AppDevPanel\Adapter\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('app_dev_panel');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable or disable the debug panel')
            ->end()
            ->arrayNode('storage')
            ->addDefaultsIfNotSet()
            ->children()
            ->scalarNode('driver')
            ->defaultValue('file')
            ->info('Storage driver: "sqlite", "file", or a fully qualified class name implementing StorageInterface')
            ->end()
            ->scalarNode('path')
            ->defaultValue('%kernel.project_dir%/var/debug')
            ->info('Directory for debug data storage')
            ->end()
            ->integerNode('history_size')
            ->defaultValue(50)
            ->info('Maximum number of debug entries to keep')
            ->end()
            ->end()
            ->end()
            ->arrayNode('collectors')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('environment')
            ->defaultTrue()
            ->end()
            ->booleanNode('request')
            ->defaultTrue()
            ->end()
            ->booleanNode('exception')
            ->defaultTrue()
            ->end()
            ->booleanNode('log')
            ->defaultTrue()
            ->end()
            ->booleanNode('event')
            ->defaultTrue()
            ->end()
            ->booleanNode('service')
            ->defaultTrue()
            ->end()
            ->booleanNode('http_client')
            ->defaultTrue()
            ->end()
            ->booleanNode('timeline')
            ->defaultTrue()
            ->end()
            ->booleanNode('var_dumper')
            ->defaultTrue()
            ->end()
            ->booleanNode('filesystem_stream')
            ->defaultTrue()
            ->end()
            ->booleanNode('http_stream')
            ->defaultTrue()
            ->end()
            ->booleanNode('command')
            ->defaultTrue()
            ->end()
            ->booleanNode('doctrine')
            ->defaultTrue()
            ->end()
            ->booleanNode('twig')
            ->defaultTrue()
            ->end()
            ->booleanNode('security')
            ->defaultTrue()
            ->end()
            ->booleanNode('cache')
            ->defaultTrue()
            ->end()
            ->booleanNode('mailer')
            ->defaultTrue()
            ->end()
            ->booleanNode('queue')
            ->defaultTrue()
            ->end()
            ->booleanNode('validator')
            ->defaultTrue()
            ->end()
            ->booleanNode('router')
            ->defaultTrue()
            ->end()
            ->booleanNode('deprecation')
            ->defaultTrue()
            ->end()
            ->booleanNode('opentelemetry')
            ->defaultTrue()
            ->end()
            ->booleanNode('translator')
            ->defaultTrue()
            ->end()
            ->booleanNode('elasticsearch')
            ->defaultTrue()
            ->end()
            ->booleanNode('redis')
            ->defaultTrue()
            ->end()
            ->booleanNode('assets')
            ->defaultTrue()
            ->info('Asset bundle collection (requires symfony/asset-mapper)')
            ->end()
            ->booleanNode('code_coverage')
            ->defaultFalse()
            ->info('Code coverage collection per request (requires pcov or xdebug)')
            ->end()
            ->end()
            ->end()
            ->arrayNode('ignored_requests')
            ->scalarPrototype()
            ->end()
            ->defaultValue(['/_wdt/**', '/_profiler/**', '/debug/**', '/inspect/**'])
            ->info('URL patterns to ignore (wildcard)')
            ->end()
            ->arrayNode('ignored_commands')
            ->scalarPrototype()
            ->end()
            ->defaultValue(['completion', 'help', 'list', 'debug:*'])
            ->info('Command name patterns to ignore (wildcard)')
            ->end()
            ->arrayNode('dumper')
            ->addDefaultsIfNotSet()
            ->children()
            ->arrayNode('excluded_classes')
            ->scalarPrototype()
            ->end()
            ->defaultValue([])
            ->info('Classes to exclude from object dumps')
            ->end()
            ->end()
            ->end()
            ->arrayNode('path_mapping')
            ->useAttributeAsKey('remote')
            ->scalarPrototype()
            ->end()
            ->defaultValue([])
            ->info('Remote-to-local path mapping for Docker/Vagrant (e.g. /app: /home/user/project)')
            ->end()
            ->arrayNode('panel')
            ->addDefaultsIfNotSet()
            ->info('Debug panel (SPA) configuration')
            ->children()
            ->scalarNode('static_url')
            ->defaultValue('')
            ->info(
                'Base URL for panel static assets (empty = GitHub Pages default). Use http://localhost:3000 for Vite dev server with HMR.',
            )
            ->end()
            ->end()
            ->end()
            ->arrayNode('toolbar')
            ->addDefaultsIfNotSet()
            ->info('Embeddable toolbar widget injected into HTML responses')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Inject the debug toolbar into HTML responses')
            ->end()
            ->scalarNode('static_url')
            ->defaultValue('')
            ->info(
                'Base URL for toolbar assets (empty = uses panel static_url). Use http://localhost:3001 for Vite dev server.',
            )
            ->end()
            ->end()
            ->end()
            ->arrayNode('api')
            ->addDefaultsIfNotSet()
            ->info('ADP API bridge configuration')
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Mount the ADP API bridge controller')
            ->end()
            ->arrayNode('allowed_ips')
            ->scalarPrototype()
            ->end()
            ->defaultValue(['127.0.0.1', '::1'])
            ->info('IP addresses allowed to access the API')
            ->end()
            ->scalarNode('auth_token')
            ->defaultValue('')
            ->info('Authentication token for API access (empty = no auth)')
            ->end()
            ->scalarNode('inspector_url')
            ->defaultNull()
            ->info(
                'Base URL of the application for MCP inspector tools (e.g. http://localhost:8080). If null, inspector tools are disabled in the HTTP MCP endpoint.',
            )
            ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}
