export enum CollectorsMap {
    // Core collectors (AppDevPanel\Kernel)
    LogCollector = 'AppDevPanel\\Kernel\\Collector\\LogCollector',
    EventCollector = 'AppDevPanel\\Kernel\\Collector\\EventCollector',
    ExceptionCollector = 'AppDevPanel\\Kernel\\Collector\\ExceptionCollector',
    ServiceCollector = 'AppDevPanel\\Kernel\\Collector\\ServiceCollector',
    TimelineCollector = 'AppDevPanel\\Kernel\\Collector\\TimelineCollector',
    HttpClientCollector = 'AppDevPanel\\Kernel\\Collector\\HttpClientCollector',
    FilesystemStreamCollector = 'AppDevPanel\\Kernel\\Collector\\Stream\\FilesystemStreamCollector',
    HttpStreamCollector = 'AppDevPanel\\Kernel\\Collector\\Stream\\HttpStreamCollector',
    ConsoleAppInfoCollector = 'AppDevPanel\\Kernel\\Collector\\Console\\ConsoleAppInfoCollector',
    WebAppInfoCollector = 'AppDevPanel\\Kernel\\Collector\\Web\\WebAppInfoCollector',
    CommandCollector = 'AppDevPanel\\Kernel\\Collector\\Console\\CommandCollector',
    RequestCollector = 'AppDevPanel\\Kernel\\Collector\\Web\\RequestCollector',
    VarDumperCollector = 'AppDevPanel\\Kernel\\Collector\\VarDumperCollector',
    EnvironmentCollector = 'AppDevPanel\\Kernel\\Collector\\EnvironmentCollector',
    DatabaseCollector = 'AppDevPanel\\Kernel\\Collector\\DatabaseCollector',
    MailerCollector = 'AppDevPanel\\Kernel\\Collector\\MailerCollector',
    AssetBundleCollector = 'AppDevPanel\\Kernel\\Collector\\AssetBundleCollector',
    MiddlewareCollector = 'AppDevPanel\\Kernel\\Collector\\MiddlewareCollector',
    QueueCollector = 'AppDevPanel\\Kernel\\Collector\\QueueCollector',
    ValidatorCollector = 'AppDevPanel\\Kernel\\Collector\\ValidatorCollector',
    ViewCollector = 'AppDevPanel\\Kernel\\Collector\\ViewCollector',
    RouterCollector = 'AppDevPanel\\Kernel\\Collector\\RouterCollector',
    CacheCollector = 'AppDevPanel\\Kernel\\Collector\\CacheCollector',
    TemplateCollector = 'AppDevPanel\\Kernel\\Collector\\TemplateCollector',
    SecurityCollector = 'AppDevPanel\\Kernel\\Collector\\SecurityCollector',
    MessageBusCollector = 'AppDevPanel\\Kernel\\Collector\\MessageBusCollector',
}
