import {playwright} from '@vitest/browser-playwright';
import {defineConfig} from 'vitest/config';

export default defineConfig({
    // Serves `mockServiceWorker.js` (generated by `npx msw init`, committed in
    // both `packages/*/public/`) at the server root so `setupWorker().start()`
    // in the browser suites can register it.
    publicDir: new URL('./packages/panel/public/', import.meta.url).pathname,
    resolve: {
        alias: {
            '@app-dev-panel/panel/': new URL('./packages/panel/src/', import.meta.url).pathname,
            '@app-dev-panel/sdk/': new URL('./packages/sdk/src/', import.meta.url).pathname,
            '@app-dev-panel/toolbar/': new URL('./packages/toolbar/src/', import.meta.url).pathname,
        },
    },
    test: {
        include: ['packages/*/src/**/*.browser.test.{ts,tsx}'],
        browser: {
            enabled: true,
            headless: true,
            provider: playwright({
                // `launchOptions` is the @vitest/browser-playwright v4 key (the
                // former `launch` key was silently ignored). CHROMIUM_PATH lets
                // CI/sandboxes point at a preinstalled binary instead of the
                // exact revision Playwright would download.
                launchOptions: {
                    executablePath: process.env.CHROMIUM_PATH || undefined,
                    args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage'],
                },
            }),
            instances: [{browser: 'chromium'}],
        },
        globals: true,
        testTimeout: 15_000,
        hookTimeout: 15_000,
        teardownTimeout: 5_000,
    },
});
